% ·▄▄▄▄  ▄▄▄ . ▌ ▐· ▄▄▄·  ▐ ▄ ▄▄▄ . ▄▄▄·  ▐ ▄ ·▄▄▄▄        
% ██▪ ██ ▀▄.▀·▪█·█▌▐█ ▀█ •█▌▐█▀▄.▀·▐█ ▀█ •█▌▐███▪ ██ ▪     
% ▐█· ▐█▌▐▀▀▪▄▐█▐█•▄█▀▀█ ▐█▐▐▌▐▀▀▪▄▄█▀▀█ ▐█▐▐▌▐█· ▐█▌ ▄█▀▄ 
% ██. ██ ▐█▄▄▌ ███ ▐█ ▪▐▌██▐█▌▐█▄▄▌▐█ ▪▐▌██▐█▌██. ██ ▐█▌.▐▌
% ▀▀▀▀▀•  ▀▀▀ . ▀   ▀  ▀ ▀▀ █▪ ▀▀▀  ▀  ▀ ▀▀ █▪▀▀▀▀▀•  ▀█▄▀▪
%
% characters.cls
% Copyright 2016 Eduardo Fernandes <edu.fernandes.pt@gmail.com>
%
% This is a custom class, based on the creativeWriting class, to allow easy creation
% of characters.
% 
% Licensed under a Creative Commons Attribution 4.0 International License.
% See https://creativecommons.org/licenses/by/4.0/
%
% Example:
% \documentclass{characters}
%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{characters}[2016/11/28 Character class]

% ●▬▬▬▬▬๑۩ Base class ۩๑▬▬▬▬▬●

\LoadClass{creativeWriting}

% Sets the page to have only the page number

%\pagestyle{fancy}
%\fancyhf{}

% Changes the titles to e displayed without the name
%\renewcommand{\chaptermark}[1]{\markright{#1}}
%\renewcommand{\sectionmark}[1]{\markright{\thesection.\ #1}}
%\renewcommand{\subsectionmark}[1]{\markright{\thesubsection.\ #1}}
%\renewcommand{\headrulewidth}{0pt}
%\fancyhead[LE,RO]{\textsl{\rightmark}}



